/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * home.java
 *
 * Created on 28 Nov 14, 4:01:42
 */
package tiketkereta;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.koneks;

/**
 *
 * @author icha
 */
public class home extends javax.swing.JFrame {
int tarif,beli,jml,hrg;
double Total;

private Connection con;
    private String[][] dataTable;
    private String[] header = {"ID","Nama","ID Kereta","Nama Kereta","Jurusan","Berangkat","Tiba","Tarif Tiket","Jumlah Beli","Jumlah Bayar"};
    /** Creates new form home */
    public home() {
        initComponents();
        koneksiDatabase();
        simpanData();
        tampilDataKeTabel();
        hapusData();
    }
public void jumlah(){
    double trf=Double.parseDouble(txtTarif.getText());
            int beli=Integer.parseInt(txtBeli.getText());
            Total = trf*beli;
            txtBayar.setText(String.valueOf(Total));
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBeli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbJurusan = new javax.swing.JComboBox();
        txtTarif = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkereta = new javax.swing.JTextField();
        txtberangkat = new javax.swing.JTextField();
        txttiba = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbkereta = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("TIKET\n KERETA API SEPUR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 11, -1, 131));

        jLabel3.setText("Nama Penumpang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 194, -1, -1));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 191, 217, -1));

        jLabel7.setText("Jurusan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 197, -1, -1));

        jLabel9.setText("Tarif Tiket");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 235, -1, -1));

        jLabel11.setText("Jumlah Beli");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 273, -1, -1));

        txtBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeliActionPerformed(evt);
            }
        });
        txtBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBeliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeliKeyReleased(evt);
            }
        });
        jPanel1.add(txtBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 270, 56, -1));

        jLabel12.setText("Jumlah Bayar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 311, -1, -1));

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 308, 134, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 204));
        jButton1.setText("BERSIH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 346, 104, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 204));
        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 346, 87, -1));

        cmbJurusan.setBackground(new java.awt.Color(204, 255, 255));
        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Jurusan--", "Purwosari - Prambanan", "Purwosari - Jogjakarta", "Purwosari - Sleman", "Purwosari - Klaten" }));
        cmbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJurusanActionPerformed(evt);
            }
        });
        jPanel1.add(cmbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 194, 164, -1));

        txtTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifActionPerformed(evt);
            }
        });
        jPanel1.add(txtTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 232, 164, -1));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 204));
        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 346, 98, -1));

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 204));
        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 346, 108, -1));

        jLabel2.setText("ID Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 163, -1, -1));
        jPanel1.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 160, 54, -1));

        jLabel4.setText("Nama Kereta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 94, -1, -1));

        jLabel5.setText("Berangkat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 135, -1, -1));

        jLabel6.setText("Tiba");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 166, -1, -1));

        txtkereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeretaActionPerformed(evt);
            }
        });
        jPanel1.add(txtkereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 91, 164, -1));

        txtberangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberangkatActionPerformed(evt);
            }
        });
        jPanel1.add(txtberangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 129, 102, -1));

        txttiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttibaActionPerformed(evt);
            }
        });
        jPanel1.add(txttiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 160, 164, -1));

        jLabel8.setText("ID Kereta");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 63, -1, -1));

        cmbkereta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih ID Kereta-", "K001", "K002", "K003" }));
        cmbkereta.setSelectedItem(cmbkereta.toString());
        cmbkereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkeretaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbkereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 60, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 720, 130));

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 153));
        jButton5.setText("Rubah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 343, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Thanks", "Selesai", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifActionPerformed

    private void cmbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJurusanActionPerformed
        // TODO add your handling code here:
        if(cmbJurusan.getSelectedItem().equals("Purwosari - Prambanan")){
            txtTarif.setText("20000");
        }else if(cmbJurusan.getSelectedItem().equals("Purwosari - Jogjakarta")){
            txtTarif.setText("30000");
        }else if(cmbJurusan.getSelectedItem().equals("Purwosari - Sleman")){
            txtTarif.setText("25000");
        }else if(cmbJurusan.getSelectedItem().equals("Purwosari - Klaten")){
            txtTarif.setText("15000");
        }else if(cmbJurusan.getSelectedItem().equals("--Pilih Jurusan--")){
            txtTarif.setText("");
        }
    }//GEN-LAST:event_cmbJurusanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        simpanData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hrg=0;
        jml=0;
        Total=0;
        txtKode.setText("");
        txtNama.setText("");
        cmbkereta.setSelectedItem("-Pilih ID Kereta-");
        txtkereta.setText("");
        cmbJurusan.setSelectedItem("--Pilih Jurusan--");
        txtberangkat.setText("");
        txttiba.setText("");
        txtBayar.setText("");
        txtBeli.setText("");
        txtTarif.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeliActionPerformed
       // TODO add your handling code here:
      
    }//GEN-LAST:event_txtBeliActionPerformed

    private void txtkeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkeretaActionPerformed

    private void txtberangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberangkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberangkatActionPerformed

    private void txttibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttibaActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
       // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBayarActionPerformed

    private void cmbkeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkeretaActionPerformed
        // TODO add your handling code here:
        if(cmbkereta.getSelectedItem().equals("K001")){
            txtkereta.setText("KA Kemplengs");
            txtberangkat.setText("08.00");
            txttiba.setText("10.00");
        }else if(cmbkereta.getSelectedItem().equals("K002")){
            txtkereta.setText("KA Endars");
            txtberangkat.setText("14.00");
            txttiba.setText("16.00");
        }else if(cmbkereta.getSelectedItem().equals("K003")){
            txtkereta.setText("KA Telkom Everywear");
            txtberangkat.setText("19.00");
            txttiba.setText("21.00");
        }else if(cmbJurusan.getSelectedItem().equals("-Pilih ID Kereta-")){
            txtkereta.setText("");
            txtberangkat.setText("");
            txttiba.setText("");
        }
    }//GEN-LAST:event_cmbkeretaActionPerformed

    private void txtBeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeliKeyPressed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtBeliKeyPressed

    private void txtBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeliKeyReleased
jumlah();                   // TODO add your handling code here:
    }//GEN-LAST:event_txtBeliKeyReleased

    private void txtBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarKeyReleased

    private void txtBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tampilDataKeTabel();// TODO add your handling code here:     
        
        
        try{
            //uji koneksi
            Statement stat = (Statement) con;
            
            //kirim perintah sql
            String sql = "UPDATE data SET id_data = ('"+txtKode.getText()+"', '"+txtNama.getText()+"','"+cmbkereta.getSelectedItem()+"','"+txtkereta.getText()+"','"+cmbJurusan.getSelectedItem()+"','"+txtberangkat.getText()+"','"+txttiba.getText()+"','"+txtTarif.getText()+"','"+txtBeli.getText()+"','"+txtBayar.getText()+"')";
            PreparedStatement p =(PreparedStatement)koneks.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            
            //ambil data
            tampilDataKeTabel();
            
            //kosongkan data
            hapusData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIPERBARUI");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void koneksiDatabase(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/keretaapi","root","");
            System.out.println("Koneksi ke MySQL Server berhasil!");
        }catch(ClassNotFoundException eclass){
            System.out.println("Driver tidak ada!");
        }catch(SQLException esql){
            System.out.println(esql.getMessage());
        }
    }
    
    private void hapusData(){
        try{
            String sql = "DELETE FROM data WHERE id_data = \""+txtKode.getText()+"\"";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Berhasil dihapus!");
        }
        catch(Exception e){
            System.out.println(e);
        }
        txtKode.setText("");
        txtNama.setText("");
        cmbkereta.setSelectedItem("-Pilih ID Kereta-");
        txtkereta.setText("");
        cmbJurusan.setSelectedItem("--Pilih Jurusan--");
        txtberangkat.setText("");
        txttiba.setText("");
        txtTarif.setText("");
        txtBeli.setText("");
        txtBayar.setText("");
        tampilDataKeTabel();
    }
    
    public void simpanData(){
        try {
            String sql = "INSERT INTO data VALUES('"+txtKode.getText()+"', '"+txtNama.getText()+"','"+cmbkereta.getSelectedItem()+"','"+txtkereta.getText()+"','"+cmbJurusan.getSelectedItem()+"','"+txtberangkat.getText()+"','"+txttiba.getText()+"','"+txtTarif.getText()+"','"+txtBeli.getText()+"','"+txtBayar.getText()+"')";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("berhasil!");
        }catch (Exception e){
            System.out.println(e);
        }
        tampilDataKeTabel();
    }
    
    
    
    public void tampilDataKeTabel(){
        ResultSet rs = null;
        try{
            Statement stmt = con.createStatement();
            rs = stmt.executeQuery("select * from data");
            
            ResultSetMetaData meta = rs.getMetaData();
            int col = meta.getColumnCount();
            int baris = 0;
            while (rs.next()){
                baris = rs.getRow();
            }
            dataTable = new String[baris][col];
            int x = 0;
            rs.beforeFirst();
            while(rs.next()){
                dataTable[x][0] = rs.getString("id_data");
                dataTable[x][1] = rs.getString("nama");
                dataTable[x][2] = rs.getString("id_kereta");
                dataTable[x][3] = rs.getString("Nama_kereta");
                dataTable[x][4] = rs.getString("jurusan");
                dataTable[x][5] = rs.getString("berangkat");
                dataTable[x][6] = rs.getString("Tiba");
                dataTable[x][7] = rs.getString("tarif");
                dataTable[x][8] = rs.getString("jumlah_beli");
                dataTable[x][9] = rs.getString("jumlah_bayar");
                x++;
            }
            jTable2.setModel(new DefaultTableModel(dataTable,header));
        }catch(Exception e){
            System.err.println("ada yang salah:"+e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbJurusan;
    private javax.swing.JComboBox cmbkereta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBeli;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTarif;
    private javax.swing.JTextField txtberangkat;
    private javax.swing.JTextField txtkereta;
    private javax.swing.JTextField txttiba;
    // End of variables declaration//GEN-END:variables

   

    private void Jumlah() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
